apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/gnunn/client
  newName: quay.io/rhtevan/client
- name: quay.io/gnunn/server
  newName: quay.io/rhtevan/server
- name: quay.io/rhtevan/client
  newName: quay.io/rhtevan/client
  newTag: b8a2b2a-2569015949
resources:
- github.com/gnunn-gitops/product-catalog/environments/overlays/dev
