apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dest-docker-config
  namespace: product-catalog-cicd
spec:
  encryptedData:
    .dockerconfigjson: AgBx0ExehotQwB93ltIyHyIEooD+TVEK4koK3WTnK7xtDAIK+BjT9prNQODt/olcUbNK+Fi48hKYVY4clxYmhZAQeKq7Kf8jTrQHaJYTIeDIXAxLrIIl0xinF7GtjoW5W6GYoF0+8mScLOjtWsN2DXoQ2CgnUFcx7qNryn7RPqqp2361Tk0dwrzBboIhPQZDbprV6g7A+Vfwj3M1JUt7C5fiacGkVYe0fbmhMSD5dL+1YLbqNK/omZxRkKByy/ibshw8X+7WPuHy68CQrQtuNgoeOoJague+DsMKmQOyuoagTOBRE5GY7Iw6xT1h/hGnrfilp5/Cw+hyTSs0MD46/rSULJc3xn0/yrjtACpsiNReDcBbCi20pqnQaD1cMlLJiAfBzd5s2eNN6LzjTMn+V3Wk1eVln1MGpahQnyujd2CILAMf9ENUyzZ9E+a/glKdX7XIkdBQE89cmU5un7wAA/sROiQN8VqD85KhEHi8xqLgptLWFWA49Nl0pl0f68+7f+5DF6Xec/riOouzI5ANSwZUR1xUERlvGE4t/K1bdrJgB5Yed1/tzlei1G1zNfCpZxaWALqydfIN7nU/ZtK+ADSOBkRFri7za4nn4HR9E7F7jD39wm57PZ5JFuzHKztUPFlHQF+mJDMCjyufFQfIMaXbTCrdZS9mue1XA/oa7gRx4EWKsu66N+mNhB3xQBh+FLU3Z592cBrbIiTS599R3nl77aNPK5a4p143x5MFdyfKRbs9tLf/of/9ggoxBdQmYRXiAwrUuq8Nh8G4V5sgLcznJRzoDfSHRqH1YVQYKLEqAnI9NzwPa7J3OSc68O61o6MISk5sBEQGNznQFGHt0k3I4d2CghSYjFcvfTR5e3Uxv/+glkEQVrytUucaZn4Nc/j1WtY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: dest-docker-config
      namespace: product-catalog-cicd
    type: kubernetes.io/dockerconfigjson

