apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/gnunn-gitops/product-catalog/environments/overlays/cicd

resources:
- pipeline-rolebinding.yaml
- argocd-env-cm.yaml

patches:
- target:
    kind: BuildConfig
    name: client
  patch: |-
    - op: replace
      path: /spec/output/to/name
      value: "quay.io/rhtevan/client:latest"
- target:
    kind: BuildConfig
    name: server
  patch: |-
    - op: replace
      path: /spec/output/to/name
      value: "quay.io/rhtevan/server:latest"
- target:
    kind: TriggerTemplate
    name: server
  patch: |-
    - op: add
      path: /spec/resourcetemplates/0/spec/params/-
      value:
        name: cluster
        value: local.home
    - op: add
      path: /spec/resourcetemplates/0/spec/params/-
      value:
        name: acs-secret
        value: roxsecrets
- target:
    kind: TriggerTemplate
    name: client
  patch: |-
    - op: add
      path: /spec/resourcetemplates/0/spec/params/-
      value:
        name: cluster
        value: local.home
    - op: add
      path: /spec/resourcetemplates/0/spec/params/-
      value:
        name: acs-secret
        value: roxsecrets
- patch: |-
    - op: replace
      path: /spec/encryptedData/.dockerconfigjson
      value: AgBx0ExehotQwB93ltIyHyIEooD+TVEK4koK3WTnK7xtDAIK+BjT9prNQODt/olcUbNK+Fi48hKYVY4clxYmhZAQeKq7Kf8jTrQHaJYTIeDIXAxLrIIl0xinF7GtjoW5W6GYoF0+8mScLOjtWsN2DXoQ2CgnUFcx7qNryn7RPqqp2361Tk0dwrzBboIhPQZDbprV6g7A+Vfwj3M1JUt7C5fiacGkVYe0fbmhMSD5dL+1YLbqNK/omZxRkKByy/ibshw8X+7WPuHy68CQrQtuNgoeOoJague+DsMKmQOyuoagTOBRE5GY7Iw6xT1h/hGnrfilp5/Cw+hyTSs0MD46/rSULJc3xn0/yrjtACpsiNReDcBbCi20pqnQaD1cMlLJiAfBzd5s2eNN6LzjTMn+V3Wk1eVln1MGpahQnyujd2CILAMf9ENUyzZ9E+a/glKdX7XIkdBQE89cmU5un7wAA/sROiQN8VqD85KhEHi8xqLgptLWFWA49Nl0pl0f68+7f+5DF6Xec/riOouzI5ANSwZUR1xUERlvGE4t/K1bdrJgB5Yed1/tzlei1G1zNfCpZxaWALqydfIN7nU/ZtK+ADSOBkRFri7za4nn4HR9E7F7jD39wm57PZ5JFuzHKztUPFlHQF+mJDMCjyufFQfIMaXbTCrdZS9mue1XA/oa7gRx4EWKsu66N+mNhB3xQBh+FLU3Z592cBrbIiTS599R3nl77aNPK5a4p143x5MFdyfKRbs9tLf/of/9ggoxBdQmYRXiAwrUuq8Nh8G4V5sgLcznJRzoDfSHRqH1YVQYKLEqAnI9NzwPa7J3OSc68O61o6MISk5sBEQGNznQFGHt0k3I4d2CghSYjFcvfTR5e3Uxv/+glkEQVrytUucaZn4Nc/j1WtY=
  target:
    kind: SealedSecret
    name: dest-docker-config
- patch: |-
    - op: replace
      path: /spec/encryptedData/email
      value: AgBQcFmp6xuOwqeUg6OmVU3QP1Wp9bvhe78jg38Ea+HUbvr0kTweo+PBIFpGk49Gpr5WvTSyw5Y62uuUaNYjZ4FPWMTmXRxC+YQoyC6lhSfluRhBU7d68CN058Be7XOD5nv76enBR7Bz3FOAr7kzbcZvPKXr2s3I2XhoofR3y7cOpcXmi8OJAxsfKlbzRkMp1o5ZxRL8BpdCflGiN5bBlZAHFX6pZhcEUGpVPjl2nBRjBaSnqbumoT+4QOxOMlur2WqSFb2+VR611v/uo0duuVxjP7EJo0VMk0zS1AoYEnnRP2ssycOMmwKPC4FroATrdd5hK/99eKJ2TcPoAYmPBhgKW7h/0SWEiqaHdn/OLuAJbUOwOr/dJBMj3I/q/efo/aBWaGfOxOtmfr0l3TRh2r/Cj8pcj28ZFwyhfdxxKBqXZCoDNRXmkBLYivme7OofE201nZ/NpQV7NxoI0QxKbLmECTa2mV/yOBDOYy/a2Va1BegYxSIWsHP5PeTf9uxOyn12CBZaeABBGR9h9llsLM0wus2Qg4maDZlsXP34LhNspSIHTq9XUylNZ4Li3fgzzZVT2sfsNIj20Llnxi9S8DZxuplKa7kAI+U+A0zzqGvbujTMG0g1SwLZO2KOcg8NqihfQ9LPKm8PXEvdsqdNiHajMbUcc99XpzaP8/Riyx8XbfcKZ9EMGQZ+RJYuewSo5yfFanKTVj0SEjJnr1KF+FjxEhGq
  target:
    kind: SealedSecret
    name: github
- patch: |-
    - op: replace
      path: /spec/encryptedData/password
      value: AgClFhFrQvscHEAnL/cP59jRhJZ6NL/d5/m1NDZztrF2U3JTfAdBAkTlbvtNrYJviCELc85R8CwsHkSQDwgh9uAlkiZuFYIQesXmFFhNHaKaqho61eAR3WUGBwn6meDXUwo3hXuZNTIbeOcVvhnEUS7hakgvZjiaB7jp4LTqhNnYRqGa20Tmq8KqeJfk2tGrOQbl1+9NMirX3513TJjesxOB9NH5x6O9yaeXpl3747PGBrIUl4SCXy9NCjFFXPx6fyeVTMhatUWFvOzDMmeQSucEPI8wDVWie1lmMTibhJVNIXJ6MQ5DG7mT8sBJkNyD+CjvQN3yiz77p8BnFiSZK87zkWlvrULvKelTdNiw5PZPN64botjGbmGg3rY7oHS8XLoPLXnmWp4ULfViRYsGyM6qtLGMm4xtQpIce3+Vl7FxuZv/5Zp2CaXN4RCFudAaa7P2bPv6TJIoURW5U0Gre1kZukqYjd1wGHTkjN4qPpjC5Z4BgJAgD2uDOQawW9CCEOnwCMdYdtJSYyLRJnsKgiHHjiFPBInPqJa14wmaz8Gsy8VCX/G4nnDkJt/e8ufbuysXqwA7sh5ZP4jm1zUiLm4JjjqzZ9WrcwP/FbaeuIEE1b11IgGMGYTM1s52xJOBPWBQlFgkdCpHABsp1uY39Gom+/kPbV7p2b8q0YEo0QwoJEMR5+j93mH+0ezebl110YObkJTDvGBBMOXOu7QPCymWS9EWUnPnEJIULhUTEoFPHG/CtU9sHdKcpNLMmd+oEoXCX+gIsJL07X8iv44BaMn390vLx+cg7CB9s/4i
  target:
    kind: SealedSecret
    name: github
- patch: |-
    - op: replace
      path: /spec/encryptedData/username
      value: AgCDKxpQ1QgiUePSHiYMOsCbidONj1p549KIxmYMgvN3BuBq+/B8QAE8fasp6Xt7090JG06jnHoNRFUi26zww2brV1z+aUUkh/2S4Ut5n8OeIbEJP9OlYiEAfFrM+bcxKuPSEXyTH+0SYNnG1I8OraJkNDXlqaHCGheCugApdh+yZf+msG2EilBGP7o8kyFRqKZqFY0hkcBrz3Uf5hcqRMtlzXfyUOwZej6okGoZ5CvEzJKRGv4tw462XqBAVTASbVwyCQiAqr/HOWeWBJgBJt6wtrq4Hobgae0dNuIGfiX5SSgm82xTE4K7gWSo86NaMlCltz3GYHL3fKHE09PaHMIvC+0YdhxbZaTzGeBTlN+05uYPaV4vocM9qSGhKAv+kZcv8Q5IQW5MwC9l0qSq2JwQ74tdhTEM+OsbVBNe+O5QXopvH4sldxKEgULcHdNmf896H0TKXIQTf3g6P+VcXIQ9veK9CuL7d0RKAhkENzuMqiGUFG3mve/i2jfHoBJIPT35seYzi3JpNF7WNiThaNQr802cB0Jcu/9kzFIGuB8pw3HebtCGiCyXDabL+Uuo3Du07UAIB2O4WtZ5hH7cUtwvRqRAfMDFiizAyQvUjsffGt8kI96IJDDIfgJeSOMRnbHHZa+/JQTQksNiBiiYOPfkKB2y2wl+Lqo3ANZBNIg0PL/YZz6EntoQmZ191ugqQ6RKw/k3FQAo
  target:
    kind: SealedSecret
    name: github

# generatorOptions:
#   disableNameSuffixHash: true

# secretGenerator:
#   - name: dest-docker-config
#     type: kubernetes.io/dockerconfigjson
#     files:
#       - secrets/.dockerconfigjson

# patchesJson6902:
#   - path: patch-pvc-block.yaml
#     target:
#       group: ""
#       kind: PersistentVolumeClaim
#       name: m2-cache
#       version: v1
  # - path: patch-pvc-block.yaml
  #   target:
  #     group: ""
  #     kind: PersistentVolumeClaim
  #     name: npm-cache
  #     version: v1

