apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/gnunn-gitops/product-catalog/environments/overlays/cicd

resources:
- pipeline-rolebinding.yaml
- argocd-env-cm.yaml

patchesStrategicMerge:
- delete-slack-sealed-secret.yaml

patches:
- target:
    kind: BuildConfig
    name: client
  patch: |-
    - op: replace
      path: /spec/output/to/name
      value: "quay.io/rhtevan/client:latest"
- target:
    kind: BuildConfig
    name: server
  patch: |-
    - op: replace
      path: /spec/output/to/name
      value: "quay.io/rhtevan/server:latest"
- target:
    kind: TriggerTemplate
    name: server
  patch: |-
    - op: add
      path: /spec/resourcetemplates/0/spec/params/-
      value:
        name: cluster
        value: local.home
    - op: add
      path: /spec/resourcetemplates/0/spec/params/-
      value:
        name: acs-secret
        value: roxsecrets
- target:
    kind: TriggerTemplate
    name: client
  patch: |-
    - op: add
      path: /spec/resourcetemplates/0/spec/params/-
      value:
        name: cluster
        value: local.home
    - op: add
      path: /spec/resourcetemplates/0/spec/params/-
      value:
        name: acs-secret
        value: roxsecrets
- patch: |-
    - op: replace
      path: /spec/encryptedData/.dockerconfigjson
      value: AgBx0ExehotQwB93ltIyHyIEooD+TVEK4koK3WTnK7xtDAIK+BjT9prNQODt/olcUbNK+Fi48hKYVY4clxYmhZAQeKq7Kf8jTrQHaJYTIeDIXAxLrIIl0xinF7GtjoW5W6GYoF0+8mScLOjtWsN2DXoQ2CgnUFcx7qNryn7RPqqp2361Tk0dwrzBboIhPQZDbprV6g7A+Vfwj3M1JUt7C5fiacGkVYe0fbmhMSD5dL+1YLbqNK/omZxRkKByy/ibshw8X+7WPuHy68CQrQtuNgoeOoJague+DsMKmQOyuoagTOBRE5GY7Iw6xT1h/hGnrfilp5/Cw+hyTSs0MD46/rSULJc3xn0/yrjtACpsiNReDcBbCi20pqnQaD1cMlLJiAfBzd5s2eNN6LzjTMn+V3Wk1eVln1MGpahQnyujd2CILAMf9ENUyzZ9E+a/glKdX7XIkdBQE89cmU5un7wAA/sROiQN8VqD85KhEHi8xqLgptLWFWA49Nl0pl0f68+7f+5DF6Xec/riOouzI5ANSwZUR1xUERlvGE4t/K1bdrJgB5Yed1/tzlei1G1zNfCpZxaWALqydfIN7nU/ZtK+ADSOBkRFri7za4nn4HR9E7F7jD39wm57PZ5JFuzHKztUPFlHQF+mJDMCjyufFQfIMaXbTCrdZS9mue1XA/oa7gRx4EWKsu66N+mNhB3xQBh+FLU3Z592cBrbIiTS599R3nl77aNPK5a4p143x5MFdyfKRbs9tLf/of/9ggoxBdQmYRXiAwrUuq8Nh8G4V5sgLcznJRzoDfSHRqH1YVQYKLEqAnI9NzwPa7J3OSc68O61o6MISk5sBEQGNznQFGHt0k3I4d2CghSYjFcvfTR5e3Uxv/+glkEQVrytUucaZn4Nc/j1WtY=
  target:
    kind: SealedSecret
    name: dest-docker-config
- patch: |-
    - op: replace
      path: /spec/encryptedData/email
      value: AgCPnHVmT/qIizwPZVYkhEFmtcVfh0SA9qjnj5Ye/6V+buq0DjwEIKeKGsW03S8fyNHpB88c3C6AXWyHWTnITVN6REwV0HaSNmdn9OCIG7peFGakTAdKjJH1CcCEFWNd/xu6mZtwkL/EJqc5zDsa45r/YEy4mUYk21Tplf3SUiigbWE4Ba0NYQOsiGkVA8gliEZrirsrqrKYKfIdKR0BgohQfHXJpq6qvBQanIMNluugZS3ey+L+K6eqq7lY3YryRKJNaCQ6JvVSfgjO8BOZeCT5hcNDGlCiOW0s72MpSBwF7yxX3RVb7qckzsN9FFGlJM9dbhzF4pOtx5caavUy1brbf7GcEtCvQXOSIGAWn1a+IOWOaulsqZCc5kcAHa707A9fcPINE8yA683F2TzHxryZAvDL8YFWfdDY1xPyEh37LneDMGPdoTL4hiIGnB6M5Hna1jXqNt7DLYB1jAqgmfvrs33Q819o5YQiVc0xfIWYaSTrucyc406TifcgIQrRzB/haXXsNhl6tvgwWTtvL2pKRuD4Qwe6gL3QFXBqA+pL35junYe2Pd3ACnH2WA0j0rfkzMBiRpj8PZXLI+K9OdjZybuEnDWlSMJTWcSSC0lBNsizfHtukVqSWyB1Xh3BHJE/yDjSFziTgZVN885wmHywvemgzWHMQkbc6ZpvnB7hygkseuoFhHjxzj5lkXjf4i2TV1z4x8RabRKl1yuRwMUeuUiV
  target:
    kind: SealedSecret
    name: github
- patch: |-
    - op: replace
      path: /spec/encryptedData/password
      value: AgB+tTiviAmqB7O5cl3zmS2KfdwSduLxHASFiN+sVsmxDSMSSHxQMPy8OsaRTCpKrkyQWnZwaRs9d0xJhgpCd518a2Z4iSeHmW1C3EE6+GztLFOh01pa0YjmQhi88Ipxk7ah7yvB9LIxUplxm16dzTWm09RsuxYodVyD2AL0K7yyYCs/TIi0ILgpxlKIR6Ei/TSdOc5j7iVf4KSTFgUHDSjicYSGe+teiJ0KeO8fSeB6Z/nbKHFqeK9+XS4dBcYqjmgNx/lOZ9fbEh5CSYAUOOGICyLyNe9iEFZxXclHxoWLev5dtgjNW+CE1IXrBZoBAAM0XavIX2TEJnh6twSeBG+lcsO5+HA6AmHAPJlQdBxbAn7d/fswvfC0uXtIn4pfJ9mxH4B6ufpZ18SUiHUGg806zv0/YJAvE50Ll5COdoyNrTJHicmRni9On4Ny7hQWrceoBmqgQTHO0bXUm4mOp91YpsGetsTKflF5pwykTm5UpkEOfQ6NBGehw9Ac9GQsDGabkOTefZAcsAkTu3r3BbS5inbOTep6emsF0mgyQrHvMy8si7HNDv85U7x8ReYAN5//wH50HLtTOtuOl0dj5tbygBs+GFoOx33tG9Znu73S7Ot3rUXN8JfO+78ZgonqcUK+/5opDgeMfmaJnHioA7WA88lgV9sMeTz3isLgegnIEtkGZAsiOiIB4v1dfo12XkhZN9t8kPEAo1sJcOlQAtqiNTMbXSDf8s+MJYH0kalDNDmh30nWWP9V
  target:
    kind: SealedSecret
    name: github
- patch: |-
    - op: replace
      path: /spec/encryptedData/username
      value: AgBF5V15o9Hi62oVzAuLgmPkmGsE64QEztmWolCup3sFdvjs0eY/RSC09yY7aobH1Cs4Z6JgpYj5jtRNj0tfyyi2ntT3kQwPHoXl2kBPoNuMADmb0YztvjtTGJ4R8WqtjX3lHDe/rhnMlVOQuGdnRDrXoypT4a6mo+kmSuWt0YnaWSfE1bRUltthP9xI7f4eCORAjgPTyT3LjOjbcuYXSRgtGc4eMm59qP6LECua0B7Hiieeqzk7HpDQfeTaKJpmxuQkw+6kpYUlJwi3aAKNAyjvOSF/SaH61RLHUZ3QdS0IVYSpW9nJFFGqBVH68O3c6stIx7C11F0mobQfcdc4Zb4fS19WsSgftNljA/yr9yJ8Pxxtn0jBhyL3U2VvyzAkwnjcngR3BCqS+158BXQ+KyIddu3Gp3Q7T1JcPS5PjZIrkh/gT96fF3EACyVnGM6Mb5mXdiC+Zz+qSDyyLHvpQtl6y/ySwO21EtEwfCehce7O7F4CUwro48CwIIbPk6CpdY8AueOF3Hja/jE0BzezgaqEy/OX45soOfhup+ktvwKxWTT9HEpQf9YOg3hY6cXbc0pvdPKyBSPz4M03muZFh6GZOYZwjJHFjBYKQY5smffsWJSjW0EvJd7IngY3EoKKP6LxhYaWKXx08rLHwr8EmvCC0kF4glhEYodUw4y8E3SgWeqlMbTkbBY0v+4wGn+9a14qIvfDry0+
  target:
    kind: SealedSecret
    name: github

# generatorOptions:
#   disableNameSuffixHash: true

# secretGenerator:
#   - name: dest-docker-config
#     type: kubernetes.io/dockerconfigjson
#     files:
#       - secrets/.dockerconfigjson

# patchesJson6902:
#   - path: patch-pvc-block.yaml
#     target:
#       group: ""
#       kind: PersistentVolumeClaim
#       name: m2-cache
#       version: v1
  # - path: patch-pvc-block.yaml
  #   target:
  #     group: ""
  #     kind: PersistentVolumeClaim
  #     name: npm-cache
  #     version: v1

