apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- github.com/gnunn-gitops/product-catalog/environments/overlays/cicd

resources:
- pipeline-rolebinding.yaml
- argocd-env-cm.yaml

patches:
- target:
    kind: TriggerTemplate
    name: server
  patch: |-
    - op: add
      path: /spec/resourcetemplates/0/spec/params/-
      value:
        name: cluster
        value: local.home
    - op: add
      path: /spec/resourcetemplates/0/spec/params/-
      value:
        name: acs-secret
        value: roxsecrets
- target:
    kind: TriggerTemplate
    name: client
  patch: |-
    - op: add
      path: /spec/resourcetemplates/0/spec/params/-
      value:
        name: cluster
        value: local.home
    - op: add
      path: /spec/resourcetemplates/0/spec/params/-
      value:
        name: acs-secret
        value: roxsecrets
- patch: |-
    - op: replace
      path: /spec/encryptedData/.dockerconfigjson
      value: AgAJ+kh3giFj0mHiiy3ytE4XX3B83uwnaSihXr2Z2rbdU5wUpFgYIZGGhBjmWtEIrQQ8QX68BOtLgxNiTt+OQXfw3taLXtoYCy4TK30GdOwczDx4WfpkB5AB8AJJ35Ubon5JCC/OS2+Tk9G9QLKFMle0tVHUVL+kOrouMtypbYz2obR88yfQJx111IRjjDtY0oMHA6JhZFoPgUNhCyXPchn1DUCL5sevG7kxAtePfNQe2/NyjnlNRiXyvYVc1gaCP2QcPFHSwgTRs5iHksZwP5YYktXZGaxSsKmJaVvu52hB6EpZJDSY5V8vuv8Iev9s99dkI54GNhDB1KOFN/xR5O7zOCoxpkaHPxOcjhVZC/fWCYhlOFRl+dkpdPYZFxjuDmh7dRJxeb821EuRWkjyhMx8VpvHGqm2lmYr37nliCVdVK+YrxOV9QNX9/7xGL5SG5jeOYwIbjceR3wDixmvBm4TQAE09qL9aXwJkQnvUExaLiOjxhGXg15TcmWUsVvdqXZDsSKXNNetn1VW1unAHUw9blMTgaX93hRhm8Qx/PsuMSFdDct4aiwfQ91nb5+7IWK01WtLSPnVfCHnqMtaYhK/hwU3Ka+OTcKm3bVF8kbK0VUlHAZ2oMDeTKBhntMtTYfuj/tvvwS0O8iD5bPsvKp/P0uxs/InqqGaQt8pFKCzvucHNW9K27e76ycZk2C2SK8H1jE3jXOfDP/J6TZqKnSn/q+8SRsyga2qIJY2O49//cD3HZdux5jSHJnO1HYfyiPxStoBbXU7WKifeQoKqaEoxtRKvzSA3+isnP7oCkQWhmxvO7r5zO6nEFa0SFleFi0OhJQ2wXx377c5hsrZmCXuycu2Nuv9+v1XazHh2R5u7X5VoLkF5L4M3AhvuFuIlAr6khg=
  target:
    kind: SealedSecret
    name: dest-docker-config
- patch: |-
    - op: replace
      path: /spec/encryptedData/email
      value: AgAlZ4a7fxuNfpYL5zPdTBjCA5Fh1De+dF4qfia5VKdJai6iRixn3aFBVmeRayDKLHFLjZ9DMAFGRbeVuNv0oijzf07GQYQTGrBVZA5U/aTZ6c8L0kswFO3WBSp8ohww4vdw8SDi1vkVMXL9SmTUPlQJUiIyZnEWDVl2H1ZbsyDIbdntjghrZxUekjJRqUmHYQDtVveeYD56amEF5lDj6NkPViRfVbeuipqoTd6CnLeVB27W1nDiy/Ycp1W2AhdGfAU+9cg9SCjcjvCkJ/UBxD6yDmzJzWqYAFSWJelrvklkI/IQO/9JCjxKAW+szUgf29hSAulLrQoLVwdqysCCTm/B5DjWqerEjSjrcElmHZH0uex6imoXbihjlIY0TCn134TuJCOsftpx/Z9i87iOW2sz42cIjdcEf2oVHqTWoq3Y4cwpUF3tghuFp/JTOK8rib9/xn72DOlB1p85gBLZRX0OxTQaV6ni7Qu3d/xks64G6BKUPLMu/eEG5v9To1S7HXEcpgWhqiTKaEFoSi3JdzgLHdHRuf6l6chH3N9Zi5GfPUPLiSj9etdKAUOBNzllxcVynvaqR6WEz8gj30ndJjG7N1m0r35uVLL67xLYyzZfaaviX8LYiPFgz8D1dvx+P5/kPbtqeonGtZbhaudNg+ssi4+4n32vHlFBjD9ZNP75Oy35yJVhmdhRzG0VP8Nn7nEqXQJEnH4iaQ0SZVVM+D+6lev4
  target:
    kind: SealedSecret
    name: github
- patch: |-
    - op: replace
      path: /spec/encryptedData/password
      value: AgBVdyotrT00wG6fQSAMpFC29Wy82UI1PpZOQ6bUt+X33/BYkZ2IXipaL3AWQ8kN4UKrgeubiu1apuNRczjgSPa26zfx/LNA36WhcsapYuBKpST7kQ8xWTGaTe5iU0KLCSiUfHqJGPF1gpsgWBp/+O4pmRoY8JHGOnQMLP8V6+amauKi5LOCHkseLJ3TC7jHW3KXUf+3mw0u8ACMR1QVYrYUY2/88ZrM+q/1lZTWAg0getipJme0JsxvfHgdgWZ5VoUlXoLFzEKbQvIFehvrGaiJ1scAx/0fcMDLQDFaaiUjApdZzZx68/lZZlcC9cH9ABHQXyxNIgqCf2L0mmY102pdOUdmzAO3a5+WA7LvnUJCkaYb2SGNLmRDcGvH/FX9dJOXSOvbeL9qS4RQ+6s8QNrQi9GDV4XypPLPsKRXXL5HIC6eaGzCFy4vKgkvwVBU5dTfdurWpE6jS2SDawGegW1yudBITtyD49RzWYRmCqTdAXT5cyCgT6g87ukiL7n889KcdsN8KcoU6j3ydlCNyFMXAV7eE/WP8RWOx1KAI8AVeVTcl0TNsxBzn1r2mmkPR3gEBOc2je5okXLDHJShENL+VGRGKdTVHN1MwY+8tHpFxsJgeU0z0MKmG6SLrp6raU6AQOvF480fOQ34Qj1FpFRh8BGqiZexViQ4moh2GlwjJR5fp8U2JLAKRmKBtCHnmr5X98R02xXLq2oICtlbCITTIv/+i/Ew4mcYZxze7XWFxL/yHPpu+FBij+IcvAP5AvR4u3S6hgltnBcl+sdFlLZEdobEEamgYhG93l+l
  target:
    kind: SealedSecret
    name: github
- patch: |-
    - op: replace
      path: /spec/encryptedData/username
      value: AgB2CYwXh4yxy023ScjOXOlWSYUt3Gx0RkxqxwkY4W4UXutvaOvBehPiIrSFiS3Z9cSWn9pE3hUN+pad6ZW7jGgNspGbjh8vcCKK0bdJFl8N3ZrfMoMND+WQyd8axq/45JqXXr1q4zCo8LtLcuW6SZpH+U6HHLmQfpRXvs/OepV6rCeq219EHDCTjsm+5NI2ggzCEVbXKFHqswYV7ArqCu3CpEOVkUMfFWLXByGHEvdsVFs+vQlGBDNoN/xIKPpyMSe5g7dhrSCikiuYXbxxJA/ZCAHmkSl/pWEXsvv0TQkIYhQ3j2ubw0WOr5jz91+Lg8oQaFmFK4QPHF3yWgSsCyFdpen2XMeak6WLBXbqtyl7/x7inizz0dUkyTteMwvOApCdfB79otq2DeoFkByHSLmcje/NfNHnhgkBd0saCc2gZwz/NrdWYc6WTZHQ/63PDW2qKUJCzlisf8aZzgqxfJDGWl1FnOJ+S58GuAgMV0uDmhxtBZzPZfTWRyJUORfRxbtj5UIJa3UZwaQ0H5VEgjQSrFr7EiQh+hUMw9AcE2cKAl7QyFzPxvEJjMh7cJjq9F+lcqxJ3qaCAiRGoiQjmViCQ5hkzcXC7N3CINAroCYyWUmLJl5TuWH34UqasSEypap3fKk+t/AxpasbZm1gLT/N2hpwwgBRJhHEAoJpvKhnbZNmSob3RZYAZKuhpMqH9jm7p3NrSHMB
  target:
    kind: SealedSecret
    name: github

# generatorOptions:
#   disableNameSuffixHash: true

# secretGenerator:
#   - name: dest-docker-config
#     type: kubernetes.io/dockerconfigjson
#     files:
#       - secrets/.dockerconfigjson

# patchesJson6902:
#   - path: patch-pvc-block.yaml
#     target:
#       group: ""
#       kind: PersistentVolumeClaim
#       name: m2-cache
#       version: v1
  # - path: patch-pvc-block.yaml
  #   target:
  #     group: ""
  #     kind: PersistentVolumeClaim
  #     name: npm-cache
  #     version: v1

